### ISSUE TITLE
sharing option

### ISSUE THREAD

**Issue by THIOYE412** [moustaphaotf/batch-contact-saver#18]
Adding a sharing option would be really nice I think.

**Comment by moustaphaotf** [comment]
Hello @THIOYE412 thank you for your enthousiasm about this project.

Can you share with me how you think of that feature ? May users be able to share their contacts, how ?

I am currently working on a feature to import data #3, you can check it out.

There is also another issue #4  for them to export group contacts into a file (that they may share by then 🥳🥳)

I'm looking forward for your PR

**Comment by moustaphaotf** [comment]
This issue is the same as #4
